export default {
  login: "King-OJ",
  id: 95216081,
  node_id: "U_kgDOBazh0Q",
  avatar_url: "https://avatars.githubusercontent.com/u/95216081?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/King-OJ",
  html_url: "https://github.com/King-OJ",
  followers_url: "https://api.github.com/users/King-OJ/followers",
  following_url: "https://api.github.com/users/King-OJ/following{/other_user}",
  gists_url: "https://api.github.com/users/King-OJ/gists{/gist_id}",
  starred_url: "https://api.github.com/users/King-OJ/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/King-OJ/subscriptions",
  organizations_url: "https://api.github.com/users/King-OJ/orgs",
  repos_url: "https://api.github.com/users/King-OJ/repos",
  events_url: "https://api.github.com/users/King-OJ/events{/privacy}",
  received_events_url: "https://api.github.com/users/King-OJ/received_events",
  type: "User",
  site_admin: false,
  name: "Clement Ojiguo",
  company: "Freelancer",
  blog: "https://king-oj.github.io/myportfolio/",
  location: "Abuja, Nigeria",
  email: null,
  hireable: null,
  bio: "Computer Science Graduate passionate about information tech. Web focused and on my journey to mobile exploration",
  twitter_username: "Talk2clemzy",
  public_repos: 25,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-11-29T09:42:36Z",
  updated_at: "2022-01-29T10:23:14Z"
  };
